import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          role: 'client' | 'attorney' | 'paralegal' | 'admin' | 'super_admin';
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
          last_login: string | null;
          preferences: Record<string, unknown>;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          role?: 'client' | 'attorney' | 'paralegal' | 'admin' | 'super_admin';
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          preferences?: Record<string, unknown>;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          role?: 'client' | 'attorney' | 'paralegal' | 'admin' | 'super_admin';
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          preferences?: Record<string, unknown>;
        };
      };
      clients: {
        Row: {
          id: string;
          user_id: string;
          ssn_last4: string | null;
          date_of_birth: string | null;
          current_address: string | null;
          previous_addresses: unknown[];
          employment_status: string | null;
          annual_income: number | null;
          credit_monitoring_service: string | null;
          primary_bureau: 'equifax' | 'experian' | 'transunion' | 'all';
          onboarding_completed: boolean;
          consent_signed_at: string | null;
          consent_ip_address: string | null;
          terms_accepted_at: string | null;
          privacy_policy_accepted_at: string | null;
          fcra_disclosure_accepted_at: string | null;
          state_of_residence: string | null;
          client_status: 'prospect' | 'active' | 'paused' | 'cancelled' | 'completed';
          assigned_attorney_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          ssn_last4?: string | null;
          date_of_birth?: string | null;
          current_address?: string | null;
          previous_addresses?: unknown[];
          employment_status?: string | null;
          annual_income?: number | null;
          credit_monitoring_service?: string | null;
          primary_bureau?: 'equifax' | 'experian' | 'transunion' | 'all';
          onboarding_completed?: boolean;
          consent_signed_at?: string | null;
          consent_ip_address?: string | null;
          terms_accepted_at?: string | null;
          privacy_policy_accepted_at?: string | null;
          fcra_disclosure_accepted_at?: string | null;
          state_of_residence?: string | null;
          client_status?: 'prospect' | 'active' | 'paused' | 'cancelled' | 'completed';
          assigned_attorney_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          ssn_last4?: string | null;
          date_of_birth?: string | null;
          current_address?: string | null;
          previous_addresses?: unknown[];
          employment_status?: string | null;
          annual_income?: number | null;
          credit_monitoring_service?: string | null;
          primary_bureau?: 'equifax' | 'experian' | 'transunion' | 'all';
          onboarding_completed?: boolean;
          consent_signed_at?: string | null;
          consent_ip_address?: string | null;
          terms_accepted_at?: string | null;
          privacy_policy_accepted_at?: string | null;
          fcra_disclosure_accepted_at?: string | null;
          state_of_residence?: string | null;
          client_status?: 'prospect' | 'active' | 'paused' | 'cancelled' | 'completed';
          assigned_attorney_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      credit_reports: {
        Row: {
          id: string;
          client_id: string;
          bureau: 'equifax' | 'experian' | 'transunion';
          report_date: string;
          report_type: 'full' | 'monitoring' | 'tri-merge';
          file_url: string | null;
          file_name: string | null;
          parsing_metadata: Record<string, unknown>;
          report_metadata: Record<string, unknown>;
          processing_status: 'pending' | 'processing' | 'processed' | 'error';
          imported_at: string;
          processed_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          client_id: string;
          bureau: 'equifax' | 'experian' | 'transunion';
          report_date: string;
          report_type?: 'full' | 'monitoring' | 'tri-merge';
          file_url?: string | null;
          file_name?: string | null;
          parsing_metadata?: Record<string, unknown>;
          report_metadata?: Record<string, unknown>;
          processing_status?: 'pending' | 'processing' | 'processed' | 'error';
          imported_at?: string;
          processed_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          client_id?: string;
          bureau?: 'equifax' | 'experian' | 'transunion';
          report_date?: string;
          report_type?: 'full' | 'monitoring' | 'tri-merge';
          file_url?: string | null;
          file_name?: string | null;
          parsing_metadata?: Record<string, unknown>;
          report_metadata?: Record<string, unknown>;
          processing_status?: 'pending' | 'processing' | 'processed' | 'error';
          imported_at?: string;
          processed_at?: string | null;
          created_by?: string | null;
        };
      };
      credit_items: {
        Row: {
          id: string;
          credit_report_id: string;
          client_id: string;
          item_type: 'tradeline' | 'inquiry' | 'public_record' | 'collection' | 'charge-off' | 'late_payment' | 'account';
          bureau: 'equifax' | 'experian' | 'transunion';
          account_name: string | null;
          account_number_partial: string | null;
          account_type: string | null;
          account_status: string | null;
          responsibility_type: string | null;
          current_balance: number | null;
          high_balance: number | null;
          credit_limit: number | null;
          payment_status: string | null;
          item_metadata: Record<string, unknown>;
          derogatory: boolean;
          dispute_candidate: boolean;
          date_opened: string | null;
          date_reported: string | null;
          date_last_payment: string | null;
          date_last_activity: string | null;
          date_closed: string | null;
          months_reviewed: number | null;
          late_30_days: number | null;
          late_60_days: number | null;
          late_90_days: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          credit_report_id: string;
          client_id: string;
          item_type: 'tradeline' | 'inquiry' | 'public_record' | 'collection' | 'charge-off' | 'late_payment' | 'account';
          bureau: 'equifax' | 'experian' | 'transunion';
          account_name?: string | null;
          account_number_partial?: string | null;
          account_type?: string | null;
          account_status?: string | null;
          responsibility_type?: string | null;
          current_balance?: number | null;
          high_balance?: number | null;
          credit_limit?: number | null;
          payment_status?: string | null;
          item_metadata?: Record<string, unknown>;
          derogatory?: boolean;
          dispute_candidate?: boolean;
          date_opened?: string | null;
          date_reported?: string | null;
          date_last_payment?: string | null;
          date_last_activity?: string | null;
          date_closed?: string | null;
          months_reviewed?: number | null;
          late_30_days?: number | null;
          late_60_days?: number | null;
          late_90_days?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          credit_report_id?: string;
          client_id?: string;
          item_type?: 'tradeline' | 'inquiry' | 'public_record' | 'collection' | 'charge-off' | 'late_payment' | 'account';
          bureau?: 'equifax' | 'experian' | 'transunion';
          account_name?: string | null;
          account_number_partial?: string | null;
          account_type?: string | null;
          account_status?: string | null;
          responsibility_type?: string | null;
          current_balance?: number | null;
          high_balance?: number | null;
          credit_limit?: number | null;
          payment_status?: string | null;
          item_metadata?: Record<string, unknown>;
          derogatory?: boolean;
          dispute_candidate?: boolean;
          date_opened?: string | null;
          date_reported?: string | null;
          date_last_payment?: string | null;
          date_last_activity?: string | null;
          date_closed?: string | null;
          months_reviewed?: number | null;
          late_30_days?: number | null;
          late_60_days?: number | null;
          late_90_days?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      disputes: {
        Row: {
          id: string;
          client_id: string;
          dispute_number: string;
          dispute_type: 'initial' | 'followup' | 'escalation' | 'method_of_verification' | 'procedural_request' | 'fcra_section_611';
          target_bureau: 'equifax' | 'experian' | 'transunion' | 'all' | null;
          status: 'draft' | 'ready' | 'submitted' | 'in_review' | 'partial_success' | 'success' | 'denied' | 'escalated' | 'closed';
          priority: 'low' | 'normal' | 'high' | 'urgent';
          submitted_at: string | null;
          bureau_response_due_date: string | null;
          response_received_at: string | null;
          bureau_response: string | null;
          bureau_response_file_url: string | null;
          fcra_days_remaining: number | null;
          fcra_extension_used: boolean;
          reviewed_by_attorney: boolean;
          attorney_reviewed_at: string | null;
          attorney_notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          dispute_number: string;
          dispute_type?: 'initial' | 'followup' | 'escalation' | 'method_of_verification' | 'procedural_request' | 'fcra_section_611';
          target_bureau?: 'equifax' | 'experian' | 'transunion' | 'all' | null;
          status?: 'draft' | 'ready' | 'submitted' | 'in_review' | 'partial_success' | 'success' | 'denied' | 'escalated' | 'closed';
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          submitted_at?: string | null;
          bureau_response_due_date?: string | null;
          response_received_at?: string | null;
          bureau_response?: string | null;
          bureau_response_file_url?: string | null;
          fcra_days_remaining?: number | null;
          fcra_extension_used?: boolean;
          reviewed_by_attorney?: boolean;
          attorney_reviewed_at?: string | null;
          attorney_notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          dispute_number?: string;
          dispute_type?: 'initial' | 'followup' | 'escalation' | 'method_of_verification' | 'procedural_request' | 'fcra_section_611';
          target_bureau?: 'equifax' | 'experian' | 'transunion' | 'all' | null;
          status?: 'draft' | 'ready' | 'submitted' | 'in_review' | 'partial_success' | 'success' | 'denied' | 'escalated' | 'closed';
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          submitted_at?: string | null;
          bureau_response_due_date?: string | null;
          response_received_at?: string | null;
          bureau_response?: string | null;
          bureau_response_file_url?: string | null;
          fcra_days_remaining?: number | null;
          fcra_extension_used?: boolean;
          reviewed_by_attorney?: boolean;
          attorney_reviewed_at?: string | null;
          attorney_notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      dispute_items: {
        Row: {
          id: string;
          dispute_id: string;
          credit_item_id: string;
          dispute_reason: string;
          dispute_reason_code: string | null;
          consumer_statement: string | null;
          requested_action: 'delete' | 'update' | 'correct' | 'investigate';
          result: 'pending' | 'deleted' | 'updated' | 'verified' | 'remains' | 'updated_as_agreed' | null;
          result_notes: string | null;
          result_date: string | null;
          verified_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          dispute_id: string;
          credit_item_id: string;
          dispute_reason: string;
          dispute_reason_code?: string | null;
          consumer_statement?: string | null;
          requested_action?: 'delete' | 'delete' | 'update' | 'correct' | 'investigate';
          result?: 'pending' | 'deleted' | 'updated' | 'verified' | 'remains' | 'updated_as_agreed' | null;
          result_notes?: string | null;
          result_date?: string | null;
          verified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dispute_id?: string;
          credit_item_id?: string;
          dispute_reason?: string;
          dispute_reason_code?: string | null;
          consumer_statement?: string | null;
          requested_action?: 'delete' | 'update' | 'correct' | 'investigate';
          result?: 'pending' | 'deleted' | 'updated' | 'verified' | 'remains' | 'updated_as_agreed' | null;
          result_notes?: string | null;
          result_date?: string | null;
          verified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          client_id: string;
          uploaded_by: string;
          document_type: 'credit_report' | 'id_verification' | 'proof_of_address' | 'dispute_letter' | 'bureau_response' | 'court_document' | 'bank_statement' | 'utility_bill' | 'other' | 'signed_agreement' | 'power_of_attorney' | 'pay_stub' | 'tax_return' | 'social_security_card' | 'birth_certificate';
          document_name: string;
          file_url: string;
          file_type: string | null;
          file_size: number | null;
          encrypted: boolean;
          encryption_key_id: string | null;
          access_level: 'client' | 'attorney' | 'both' | 'admin';
          verified: boolean;
          verified_by: string | null;
          verified_at: string | null;
          document_metadata: Record<string, unknown>;
          retention_until: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          uploaded_by: string;
          document_type: 'credit_report' | 'id_verification' | 'proof_of_address' | 'dispute_letter' | 'bureau_response' | 'court_document' | 'bank_statement' | 'utility_bill' | 'other' | 'signed_agreement' | 'power_of_attorney' | 'pay_stub' | 'tax_return' | 'social_security_card' | 'birth_certificate';
          document_name: string;
          file_url: string;
          file_type?: string | null;
          file_size?: number | null;
          encrypted?: boolean;
          encryption_key_id?: string | null;
          access_level?: 'client' | 'attorney' | 'both' | 'admin';
          verified?: boolean;
          verified_by?: string | null;
          verified_at?: string | null;
          document_metadata?: Record<string, unknown>;
          retention_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          uploaded_by?: string;
          document_type?: 'credit_report' | 'id_verification' | 'proof_of_address' | 'dispute_letter' | 'bureau_response' | 'court_document' | 'bank_statement' | 'utility_bill' | 'other' | 'signed_agreement' | 'power_of_attorney' | 'pay_stub' | 'tax_return' | 'social_security_card' | 'birth_certificate';
          document_name?: string;
          file_url?: string;
          file_type?: string | null;
          file_size?: number | null;
          encrypted?: boolean;
          encryption_key_id?: string | null;
          access_level?: 'client' | 'attorney' | 'both' | 'admin';
          verified?: boolean;
          verified_by?: string | null;
          verified_at?: string | null;
          document_metadata?: Record<string, unknown>;
          retention_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      communications: {
        Row: {
          id: string;
          client_id: string;
          sender_id: string;
          recipient_id: string | null;
          comm_type: 'message' | 'call_log' | 'email' | 'video_call' | 'system_notification';
          direction: 'inbound' | 'outbound';
          subject: string | null;
          body: string | null;
          compliance_compliant: boolean;
          consent_verified_at: string | null;
          comm_metadata: Record<string, unknown>;
          read_at: string | null;
          attachments: unknown[];
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          sender_id: string;
          recipient_id?: string | null;
          comm_type: 'message' | 'call_log' | 'email' | 'video_call' | 'system_notification';
          direction: 'inbound' | 'outbound';
          subject?: string | null;
          body?: string | null;
          compliance_compliant?: boolean;
          consent_verified_at?: string | null;
          comm_metadata?: Record<string, unknown>;
          read_at?: string | null;
          attachments?: unknown[];
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          sender_id?: string;
          recipient_id?: string | null;
          comm_type?: 'message' | 'call_log' | 'email' | 'video_call' | 'system_notification';
          direction?: 'inbound' | 'outbound';
          subject?: string | null;
          body?: string | null;
          compliance_compliant?: boolean;
          consent_verified_at?: string | null;
          comm_metadata?: Record<string, unknown>;
          read_at?: string | null;
          attachments?: unknown[];
          created_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          client_id: string | null;
          dispute_id: string | null;
          assigned_to: string | null;
          task_type: 'import_report' | 'review_report' | 'initiate_dispute' | 'follow_up' | 'client_communication' | 'document_review' | 'approval_needed' | 'bureau_followup' | 'escalation' | 're-import';
          title: string;
          description: string | null;
          priority: 'low' | 'normal' | 'high' | 'urgent';
          status: 'pending' | 'in_progress' | 'completed' | 'cancelled' | 'overdue';
          due_date: string | null;
          completed_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id?: string | null;
          dispute_id?: string | null;
          assigned_to?: string | null;
          task_type: 'import_report' | 'review_report' | 'initiate_dispute' | 'follow_up' | 'client_communication' | 'document_review' | 'approval_needed' | 'bureau_followup' | 'escalation' | 're-import';
          title: string;
          description?: string | null;
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          status?: 'pending' | 'in_progress' | 'completed' | 'cancelled' | 'overdue';
          due_date?: string | null;
          completed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string | null;
          dispute_id?: string | null;
          assigned_to?: string | null;
          task_type?: 'import_report' | 'review_report' | 'initiate_dispute' | 'follow_up' | 'client_communication' | 'document_review' | 'approval_needed' | 'bureau_followup' | 'escalation' | 're-import';
          title?: string;
          description?: string | null;
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          status?: 'pending' | 'in_progress' | 'completed' | 'cancelled' | 'overdue';
          due_date?: string | null;
          completed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      credit_score_snapshots: {
        Row: {
          id: string;
          client_id: string;
          bureau: 'equifax' | 'experian' | 'transunion' | 'combined';
          score: number | null;
          score_model: string;
          score_date: string;
          change_from_prior: number | null;
          improvement_goal: number | null;
          score_metadata: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          bureau: 'equifax' | 'experian' | 'transunion' | 'combined';
          score?: number | null;
          score_model?: string;
          score_date: string;
          change_from_prior?: number | null;
          improvement_goal?: number | null;
          score_metadata?: Record<string, unknown>;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          bureau?: 'equifax' | 'experian' | 'transunion' | 'combined';
          score?: number | null;
          score_model?: string;
          score_date?: string;
          change_from_prior?: number | null;
          improvement_goal?: number | null;
          score_metadata?: Record<string, unknown>;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          client_id: string;
          plan_id: string;
          plan_name: string | null;
          status: 'trial' | 'active' | 'paused' | 'cancelled' | 'expired';
          amount_cents: number | null;
          billing_cycle: 'monthly' | 'quarterly' | 'annual';
          current_period_start: string | null;
          current_period_end: string | null;
          stripe_subscription_id: string | null;
          stripe_customer_id: string | null;
          cancel_at_period_end: boolean;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          plan_id: string;
          plan_name?: string | null;
          status?: 'trial' | 'active' | 'paused' | 'cancelled' | 'expired';
          amount_cents?: number | null;
          billing_cycle?: 'monthly' | 'quarterly' | 'annual';
          current_period_start?: string | null;
          current_period_end?: string | null;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          cancel_at_period_end?: boolean;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          plan_id?: string;
          plan_name?: string | null;
          status?: 'trial' | 'active' | 'paused' | 'cancelled' | 'expired';
          amount_cents?: number | null;
          billing_cycle?: 'monthly' | 'quarterly' | 'annual';
          current_period_start?: string | null;
          current_period_end?: string | null;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          cancel_at_period_end?: boolean;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      consent_records: {
        Row: {
          id: string;
          client_id: string;
          consent_type: 'terms_of_service' | 'privacy_policy' | 'fcra_disclosure' | 'croa_disclosure' | 'electronic_signature_consent' | 'credit_pull_authorization' | 'representation_agreement' | 'communication_consent' | 'data_processing';
          version: string;
          content: string | null;
          signed_at: string;
          ip_address: string;
          user_agent: string | null;
          document_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          consent_type: 'terms_of_service' | 'privacy_policy' | 'fcra_disclosure' | 'croa_disclosure' | 'electronic_signature_consent' | 'credit_pull_authorization' | 'representation_agreement' | 'communication_consent' | 'data_processing';
          version: string;
          content?: string | null;
          signed_at: string;
          ip_address: string;
          user_agent?: string | null;
          document_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          consent_type?: 'terms_of_service' | 'privacy_policy' | 'fcra_disclosure' | 'croa_disclosure' | 'electronic_signature_consent' | 'credit_pull_authorization' | 'representation_agreement' | 'communication_consent' | 'data_processing';
          version?: string;
          content?: string | null;
          signed_at?: string;
          ip_address?: string;
          user_agent?: string | null;
          document_url?: string | null;
          created_at?: string;
        };
      };
      letter_templates: {
        Row: {
          id: string;
          name: string;
          template_type: string;
          description: string | null;
          subject_template: string | null;
          body_template: string;
          applicable_bureaus: string[];
          is_active: boolean;
          attorney_approved: boolean;
          approved_by: string | null;
          approved_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          template_type: string;
          description?: string | null;
          subject_template?: string | null;
          body_template: string;
          applicable_bureaus?: string[];
          is_active?: boolean;
          attorney_approved?: boolean;
          approved_by?: string | null;
          approved_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          template_type?: string;
          description?: string | null;
          subject_template?: string | null;
          body_template?: string;
          applicable_bureaus?: string[];
          is_active?: boolean;
          attorney_approved?: boolean;
          approved_by?: string | null;
          approved_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      dispute_letters: {
        Row: {
          id: string;
          dispute_id: string;
          letter_type: string;
          letter_template_id: string | null;
          recipient_type: 'credit_bureau' | 'data_furnisher' | 'both' | null;
          recipient_bureau: string | null;
          recipient_address: string | null;
          subject_line: string | null;
          body_content: string;
          generated_at: string;
          generated_by: string | null;
          approved_by_attorney: string | null;
          approved_at: string | null;
          file_url: string | null;
          file_name: string | null;
          sent_at: string | null;
          tracking_number: string | null;
          certified_mail: boolean;
          contains_pii: boolean;
          encryption_applied: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          dispute_id: string;
          letter_type: string;
          letter_template_id?: string | null;
          recipient_type?: 'credit_bureau' | 'data_furnisher' | 'both' | null;
          recipient_bureau?: string | null;
          recipient_address?: string | null;
          subject_line?: string | null;
          body_content: string;
          generated_at?: string;
          generated_by?: string | null;
          approved_by_attorney?: string | null;
          approved_at?: string | null;
          file_url?: string | null;
          file_name?: string | null;
          sent_at?: string | null;
          tracking_number?: string | null;
          certified_mail?: boolean;
          contains_pii?: boolean;
          encryption_applied?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          dispute_id?: string;
          letter_type?: string;
          letter_template_id?: string | null;
          recipient_type?: 'credit_bureau' | 'data_furnisher' | 'both' | null;
          recipient_bureau?: string | null;
          recipient_address?: string | null;
          subject_line?: string | null;
          body_content?: string;
          generated_at?: string;
          generated_by?: string | null;
          approved_by_attorney?: string | null;
          approved_at?: string | null;
          file_url?: string | null;
          file_name?: string | null;
          sent_at?: string | null;
          tracking_number?: string | null;
          certified_mail?: boolean;
          contains_pii?: boolean;
          encryption_applied?: boolean;
          created_at?: string;
        };
      };
      attorney_escalations: {
        Row: {
          id: string;
          client_id: string;
          dispute_id: string | null;
          escalation_number: string;
          escalation_type: 'dispute_escalation' | 'cfpb_complaint' | 'ftc_complaint' | 'debt_validation' | 'cease_desist' | 'litigation_threat' | 'identity_theft_affidavit' | 'goodwill_intervention' | 'arbitration';
          status: 'pending_review' | 'attorney_assigned' | 'in_progress' | 'action_taken' | 'resolved' | 'closed_no_action' | 'escalated_litigation';
          priority: 'low' | 'normal' | 'high' | 'urgent' | 'critical';
          assigned_attorney_id: string | null;
          assigned_at: string | null;
          attorney_notes: string | null;
          legal_basis: string | null;
          requested_remedy: string | null;
          creditor_name: string | null;
          creditor_address: string | null;
          account_number_partial: string | null;
          disputed_amount: number | null;
          client_description: string | null;
          action_taken_at: string | null;
          action_description: string | null;
          outcome: string | null;
          outcome_date: string | null;
          supporting_documents: unknown[];
          generated_letter_url: string | null;
          response_deadline: string | null;
          statute_of_limitations: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          dispute_id?: string | null;
          escalation_number: string;
          escalation_type: 'dispute_escalation' | 'cfpb_complaint' | 'ftc_complaint' | 'debt_validation' | 'cease_desist' | 'litigation_threat' | 'identity_theft_affidavit' | 'goodwill_intervention' | 'arbitration';
          status?: 'pending_review' | 'attorney_assigned' | 'in_progress' | 'action_taken' | 'resolved' | 'closed_no_action' | 'escalated_litigation';
          priority?: 'low' | 'normal' | 'high' | 'urgent' | 'critical';
          assigned_attorney_id?: string | null;
          assigned_at?: string | null;
          attorney_notes?: string | null;
          legal_basis?: string | null;
          requested_remedy?: string | null;
          creditor_name?: string | null;
          creditor_address?: string | null;
          account_number_partial?: string | null;
          disputed_amount?: number | null;
          client_description?: string | null;
          action_taken_at?: string | null;
          action_description?: string | null;
          outcome?: string | null;
          outcome_date?: string | null;
          supporting_documents?: unknown[];
          generated_letter_url?: string | null;
          response_deadline?: string | null;
          statute_of_limitations?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'pending_review' | 'attorney_assigned' | 'in_progress' | 'action_taken' | 'resolved' | 'closed_no_action' | 'escalated_litigation';
          priority?: 'low' | 'normal' | 'high' | 'urgent' | 'critical';
          assigned_attorney_id?: string | null;
          assigned_at?: string | null;
          attorney_notes?: string | null;
          action_taken_at?: string | null;
          action_description?: string | null;
          outcome?: string | null;
          outcome_date?: string | null;
          updated_at?: string;
        };
      };
      escalation_messages: {
        Row: {
          id: string;
          escalation_id: string;
          sender_id: string;
          message: string;
          is_attorney: boolean;
          is_internal: boolean;
          attachments: unknown[];
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          escalation_id: string;
          sender_id: string;
          message: string;
          is_attorney?: boolean;
          is_internal?: boolean;
          attachments?: unknown[];
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          read_at?: string | null;
        };
      };
    };
  };
};
